[package]
name = "photo-engine"
version = "0.3.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
suite-core = { path = "../core", package = "suite-core" }
datatypes = { path = "../datatypes" }
image = { workspace = true }
rayon = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
pollster = { workspace = true }
iced = { workspace = true, features = ["image"] }
