[package]
name = "ui"
version = "0.2.0"
authors = ["vabyz971 <vabyz971@gmail.com>"]
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
iced = { workspace = true, features = ["svg", "canvas", "image"] }
iced_aw.workspace = true
iced_core = "0.14"
bytemuck = { workspace = true }
pollster = { workspace = true }
datatypes = { path = "../core/datatypes" }
suite-core = { path = "../core/core", package = "suite-core" }
suite-shell = { path = "../core/shell" }
